# Generated by Django 6.0.3 on 2026-05-16 00:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('acao', 'Ação'), ('fii', 'Fundo Imobiliário'), ('renda_fixa', 'Renda Fixa'), ('fundo', 'Fundo de Investimento'), ('cripto', 'Criptomoeda'), ('outro', 'Outro')], max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_aplicacao', models.DateField()),
                ('cotacao_atualizada_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
