# Generated by Django 6.0.3 on 2026-05-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='tipo',
            field=models.CharField(choices=[('acao', 'Ação'), ('fii', 'Fundo Imobiliário'), ('tesouro', 'Tesouro Direto'), ('renda_fixa', 'Renda Fixa'), ('fundo', 'Fundo de Investimento'), ('cripto', 'Criptomoeda'), ('outro', 'Outro')], max_length=20),
        ),
    ]
