# Generated by Django 6.0.3 on 2026-05-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_investment_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesouroTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('vencimento', models.DateField()),
                ('data_base', models.DateField()),
                ('pu_compra', models.DecimalField(decimal_places=4, max_digits=14)),
                ('pu_venda', models.DecimalField(decimal_places=4, max_digits=14)),
                ('taxa_compra', models.DecimalField(decimal_places=4, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo', 'vencimento'],
                'unique_together': {('tipo', 'vencimento')},
            },
        ),
    ]
