# Generated by Django 6.0.3 on 2026-05-16 01:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_tesourotitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='pu_atual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='data_aplicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='valor_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='investment',
            name='valor_atual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.CreateModel(
            name='InvestmentMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra / Aporte'), ('venda', 'Resgate / Venda')], max_length=10)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=14)),
                ('pu_na_data', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='investments.investment')),
            ],
            options={
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TesouroPrecoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('vencimento', models.DateField()),
                ('data', models.DateField()),
                ('pu_compra', models.DecimalField(decimal_places=4, max_digits=14)),
                ('pu_venda', models.DecimalField(decimal_places=4, max_digits=14)),
            ],
            options={
                'indexes': [models.Index(fields=['tipo', 'vencimento', 'data'], name='investments_tipo_6dbc99_idx')],
                'unique_together': {('tipo', 'vencimento', 'data')},
            },
        ),
    ]
