# Generated by Django 6.0.3 on 2026-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_update_tesouro_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='ticker',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
