# Generated by Django 6.0.3 on 2026-05-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_update_tesouro_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmovimentacao',
            name='taxa_na_data',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tesouroprecohistorico',
            name='taxa_compra',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
