# Generated by Django 6.0.3 on 2026-04-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_conta_add_user_agency_nickname'),
        ('transactions', '0003_category_model_and_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accounts.conta', verbose_name='Conta Bancária'),
        ),
    ]
