# Generated by Django 6.0.3 on 2026-05-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
