# Generated by Django 6.0.3 on 2026-05-16 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_end_date'),
        ('transactions', '0006_transaction_is_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.subscription', verbose_name='Assinatura'),
        ),
    ]
